# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('comment', models.CharField(max_length=512, verbose_name='comment')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='delivered'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Nova Poshta'), (1, 'Nova Poshta courier'), (2, 'Odessa courier'), (2, 'Another')], default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'In Nova Poshta branch'), (1, 'Cash on delivery'), (2, 'Private terminal'), (3, 'Online payment')], default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
    ]
