# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20161026_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='archived',
        ),
        migrations.AddField(
            model_name='orders',
            name='date_of_delivery',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date_of_delivery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Nova Poshta'), (1, 'Nova Poshta courier'), (2, 'Odessa courier'), (2, 'Another')], default=0, verbose_name='delivery_method'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'In Nova Poshta branch'), (1, 'Cash on delivery'), (2, 'Private terminal'), (3, 'Online payment')], default=0, verbose_name='payment_method'),
        ),
    ]
