# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20161028_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_comment',
            field=models.CharField(default='', max_length=512, verbose_name='user comment'),
            preserve_default=False,
        ),
    ]
