# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_of_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_of_delivery'),
        ),
    ]
