# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20161104_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='data')),
                ('sign', models.TextField(verbose_name='sign')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
        ),
    ]
