# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_paymentraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='liqpay_wait_accept',
            field=models.BooleanField(default=False, verbose_name='LiqPay wait accept'),
        ),
    ]
