# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_liqpay_wait_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentraw',
            name='data_decoded',
            field=models.TextField(default='', verbose_name='data decoded'),
            preserve_default=False,
        ),
    ]
