# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orders_lang_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Warehouse-to-warehouse delivery at the nearest Nova Poshta branch (in Ukraine);'), (1, 'Nova Poshta door-to-door delivery (in Ukraine);'), (2, 'Courier delivery across Odessa;'), (3, 'Worldwide Delivery.')], default=0, verbose_name='delivery_method'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(3, 'Via LiqPay (onlive);'), (2, 'By any other bank Visa or MasterCard;'), (1, 'Settle in cash in the case of courier "door-to-door" delivery;'), (0, 'Cash on delivery upon receipt of order at the Nova Poshta branch;'), (5, 'Through any system of international money transfer (in the case of overseas delivery).')], default=0, verbose_name='payment_method'),
        ),
    ]
