# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitems_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='packed',
            field=models.BooleanField(default=False, verbose_name='Packed'),
        ),
    ]
