# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orders_packed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='phone')),
                ('news', models.BooleanField(default=False, verbose_name='news')),
                ('lang_code', models.CharField(blank=True, default='ru', max_length=2, verbose_name='lang code')),
            ],
            options={
                'verbose_name_plural': 'Phone',
                'verbose_name': 'Phone',
                'ordering': ('phone',),
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Code')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Discount')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
            ],
            options={
                'verbose_name_plural': 'code',
                'verbose_name': 'code',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='comment',
            field=models.CharField(blank=True, max_length=512, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount_promo',
            field=models.PositiveIntegerField(default=0, verbose_name='discount from promo'),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount_stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='discount from stocks'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(db_index=True, max_length=32, verbose_name='phone'),
        ),
    ]
