# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20161212_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='discount from stocks'),
        ),
        migrations.AddField(
            model_name='phones',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='phone'),
        ),
    ]
