# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0013_auto_20161223_1554'),
        ('orders', '0022_auto_20170131_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CartSet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Sizes')),
            ],
        ),
    ]
