# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orders_discount_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Warehouse-to-warehouse delivery at the nearest Nova Poshta branch (in Ukraine);'), (1, 'Nova Poshta door-to-door delivery (in Ukraine);'), (2, ''), (3, 'Worldwide Delivery.')], default=0, verbose_name='delivery_method'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='discount_promo',
            field=models.PositiveIntegerField(default=0, verbose_name='discount from promo (percent)'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(3, 'Via LiqPay (onlive);'), (2, 'By any other bank Visa or MasterCard;'), (1, ''), (0, 'Cash on delivery upon receipt of order at the Nova Poshta branch;'), (5, '')], default=0, verbose_name='payment_method'),
        ),
    ]
