# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orders_delivery_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigth_from', models.PositiveSmallIntegerField()),
                ('weigth_to', models.PositiveSmallIntegerField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Countris')),
            ],
            options={
                'ordering': ('country',),
                'verbose_name_plural': 'Delivery_Cost',
                'verbose_name': 'Delivery_Cost',
            },
        ),
    ]
