# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_deliverycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='countris',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='countris',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='countris',
            name='name_uk',
            field=models.CharField(max_length=70, null=True, verbose_name='Country'),
        ),
    ]
