# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20171011_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countris',
            name='name',
            field=models.CharField(max_length=70, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='countris',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='countris',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='countris',
            name='name_uk',
            field=models.CharField(max_length=70, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(3, 'Pay by card (Visa, MasterCard);'), (2, 'PrivatBank (Ukraine only);'), (1, ''), (0, 'Cash on delivery upon receipt of order at the Nova Poshta branch;'), (5, '')], default=0, verbose_name='payment_method'),
        ),
    ]
