# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orders_wfp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='wfp_status',
            field=models.CharField(default='', max_length=512, verbose_name='WFP status'),
        ),
    ]
