# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20180514_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentraw',
            name='data_decoded',
            field=models.TextField(default='', verbose_name='data decoded'),
        ),
    ]
