# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20180514_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='wfp_status',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='WFP status'),
        ),
        migrations.AlterField(
            model_name='paymentraw',
            name='data_decoded',
            field=models.TextField(blank=True, default='', verbose_name='data decoded'),
        ),
    ]
