# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20180514_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Warehouse-to-warehouse delivery at the nearest Nova Poshta branch (in Ukraine);'), (1, 'Nova Poshta door-to-door delivery (in Ukraine);'), (3, 'Worldwide Delivery.'), (2, 'In showroom')], default=0, verbose_name='delivery_method'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(choices=[(3, 'Pay by card (Visa, MasterCard);'), (2, 'PrivatBank (Ukraine only);'), (1, ''), (0, 'Cash on delivery upon receipt of order at the Nova Poshta branch;'), (5, 'Cash in showroom')], default=0, verbose_name='payment_method'),
        ),
    ]
