# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0031_items_details_rozetka'),
        ('orders', '0037_orders_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IWant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='first name')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('lang_code', models.CharField(blank=True, default='ru', max_length=2, verbose_name='lang code')),
                ('status', models.PositiveIntegerField(choices=[(0, 'New'), (1, 'Viewedl'), (2, 'Made'), (3, 'Sent')], default=0, verbose_name='new status')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
            ],
            options={
                'verbose_name_plural': 'I want',
                'ordering': ('-added',),
                'verbose_name': 'I want',
            },
        ),
    ]
