# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20200214_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iwant',
            name='status',
            field=models.PositiveIntegerField(choices=[(100, 'Новый'), (200, 'Просмотрено'), (300, 'Изготовлено'), (400, 'Отправлено')], default=100, verbose_name='new status'),
        ),
    ]
