# Generated by Django 3.1.2 on 2020-12-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20200409_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', models.TextField(verbose_name='city name ru')),
                ('description', models.TextField(verbose_name='city name')),
                ('ref', models.CharField(db_index=True, max_length=40, verbose_name='ref')),
                ('settlement_type_description', models.TextField(verbose_name='settlement type description')),
                ('settlement_type_description_ru', models.TextField(verbose_name='settlement type description ru')),
                ('area_description', models.TextField(verbose_name='area description')),
                ('area_description_ru', models.TextField(verbose_name='area description ru')),
            ],
            options={
                'verbose_name': 'Nova_Poshta_Cities',
                'verbose_name_plural': 'Nova_Poshta_Cities',
                'ordering': ('description_ru',),
            },
        ),
        migrations.CreateModel(
            name='NovaPoshtaWarehouses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_ru', models.TextField(verbose_name='warehouses name')),
                ('description', models.TextField(verbose_name='warehouses name')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('ref', models.CharField(db_index=True, max_length=40, verbose_name='ref')),
                ('novaposhtacities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.novaposhtacities')),
            ],
            options={
                'verbose_name': 'Nova_Poshta_Warehouses',
                'verbose_name_plural': 'Nova_Poshta_Warehouses',
                'ordering': ('description_ru',),
            },
        ),
    ]
