# Generated by Django 3.1.2 on 2020-12-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_novaposhtacities_novaposhtawarehouses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novaposhtacities',
            options={'ordering': ('description',), 'verbose_name': 'Nova_Poshta_Cities', 'verbose_name_plural': 'Nova_Poshta_Cities'},
        ),
        migrations.AlterModelOptions(
            name='novaposhtawarehouses',
            options={'ordering': ('description',), 'verbose_name': 'Nova_Poshta_Warehouses', 'verbose_name_plural': 'Nova_Poshta_Warehouses'},
        ),
        migrations.RemoveField(
            model_name='novaposhtacities',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='novaposhtawarehouses',
            name='description_ru',
        ),
    ]
