# Generated by Django 3.1.2 on 2020-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20201213_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtacities',
            name='description_en',
            field=models.TextField(null=True, verbose_name='city name'),
        ),
        migrations.AddField(
            model_name='novaposhtacities',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='city name'),
        ),
        migrations.AddField(
            model_name='novaposhtacities',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='city name'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouses',
            name='description_en',
            field=models.TextField(null=True, verbose_name='warehouses name'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouses',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='warehouses name'),
        ),
        migrations.AddField(
            model_name='novaposhtawarehouses',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='warehouses name'),
        ),
    ]
