# Generated by Django 3.1.2 on 2020-12-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20201213_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPoshtaRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='city name')),
                ('description_ru', models.TextField(null=True, verbose_name='city name')),
                ('description_uk', models.TextField(null=True, verbose_name='city name')),
                ('description_en', models.TextField(null=True, verbose_name='city name')),
                ('ref', models.CharField(db_index=True, max_length=40, verbose_name='ref')),
                ('areasenter_ref', models.CharField(db_index=True, max_length=40, verbose_name='areasenter_ref')),
            ],
            options={
                'verbose_name': 'Nova_Poshta_Cities',
                'verbose_name_plural': 'Nova_Poshta_Cities',
                'ordering': ('description',),
            },
        ),
        migrations.AlterField(
            model_name='novaposhtawarehouses',
            name='novaposhtacities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.novaposhtacities'),
        ),
        migrations.AddField(
            model_name='novaposhtacities',
            name='novaposhtaregions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.novaposhtaregions'),
        ),
    ]
