# Generated by Django 3.1.2 on 2021-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20201213_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Warehouse-to-warehouse delivery at the nearest Nova Poshta branch (in Ukraine);'), (1, 'Nova Poshta door-to-door delivery (in Ukraine);'), (3, 'Worldwide Delivery.'), (2, 'In showroom'), (4, 'Justin')], default=0, verbose_name='delivery_method'),
        ),
    ]
