# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='amount')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advent',
                'verbose_name': 'Advent',
            },
        ),
        migrations.CreateModel(
            name='Advent_tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='amount')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advent',
                'verbose_name': 'Advent',
            },
        ),
        migrations.CreateModel(
            name='Corrections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='amount')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Corrections',
                'verbose_name': 'Corrections',
            },
        ),
    ]
