# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0002_auto_20161001_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastOrdersCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='datetime')),
            ],
        ),
    ]
