# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='amount')),
            ],
            options={
                'verbose_name_plural': 'Amount of items',
                'verbose_name': 'Amount of items',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('name_ru', models.CharField(max_length=70, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=70, null=True, verbose_name='name')),
                ('icon_a', models.ImageField(blank=True, default='', editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('icon_b', models.ImageField(blank=True, default='', editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('icon_c', models.ImageField(blank=True, default='', editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('details_ru', models.TextField(blank=True, null=True, verbose_name='details')),
                ('details_en', models.TextField(blank=True, null=True, verbose_name='details')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
            ],
            options={
                'verbose_name_plural': 'Categories of items',
                'verbose_name': 'Categories of items',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Fashions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=70, verbose_name='name')),
                ('name_ru', models.CharField(default='No name', max_length=70, null=True, verbose_name='name')),
                ('name_en', models.CharField(default='No name', max_length=70, null=True, verbose_name='name')),
                ('icon_a', models.ImageField(blank=True, default='', editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('icon_b', models.ImageField(blank=True, default='', editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('icon_c', models.ImageField(blank=True, default='', editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('details_ru', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('details_en', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Categories')),
            ],
            options={
                'verbose_name_plural': 'Fashions of items',
                'verbose_name': 'Fashions of items',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('small_image', models.ImageField(blank=True, editable=False, upload_to='small_photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('details_ru', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('details_en', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='price')),
                ('price_description', models.CharField(default='Grn.', max_length=250, verbose_name='price_description')),
                ('price_description_ru', models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description')),
                ('price_description_en', models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description')),
                ('views_per_month', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('fashions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Fashions')),
            ],
            options={
                'verbose_name_plural': 'items',
                'verbose_name': 'items',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='Items_views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
            ],
            options={
                'verbose_name_plural': 'Photo',
                'verbose_name': 'Photo',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Categories')),
            ],
            options={
                'verbose_name_plural': 'Sizes of items',
                'verbose_name': 'Sizes of items',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items'),
        ),
        migrations.AddField(
            model_name='balance',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Sizes'),
        ),
    ]
