# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:11
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('added',), 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='image_small',
            field=django_resized.forms.ResizedImageField(default='', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
