# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:22
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0002_auto_20160926_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='small_image',
        ),
        migrations.AddField(
            model_name='items',
            name='image_small',
            field=django_resized.forms.ResizedImageField(default='', upload_to='small_photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=django_resized.forms.ResizedImageField(upload_to='small_photos/%Y/%m/%d'),
        ),
    ]
