# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0003_auto_20160926_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
        ),
    ]
