# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0004_auto_20160927_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='icon_a',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='icon_b',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='icon_c',
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=django_resized.forms.ResizedImageField(default='', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(default='', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fashions',
            name='icon_a',
            field=models.ImageField(blank=True, default='', upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='icon_b',
            field=models.ImageField(blank=True, default='', upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='icon_c',
            field=models.ImageField(blank=True, default='', upload_to='small_photos/%Y/%m/%d'),
        ),
    ]
