# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:47
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0005_auto_20160927_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashions',
            name='icon_a',
        ),
        migrations.RemoveField(
            model_name='fashions',
            name='icon_b',
        ),
        migrations.RemoveField(
            model_name='fashions',
            name='icon_c',
        ),
        migrations.AddField(
            model_name='fashions',
            name='image',
            field=django_resized.forms.ResizedImageField(default='', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashions',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(default='', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
