# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0005_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elephants.Categories'),
        ),
    ]
