# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0006_auto_20160927_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.IntegerField(verbose_name='old value')),
                ('new_value', models.IntegerField(verbose_name='new value')),
                ('change_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ('id',), 'verbose_name': 'Amount of items', 'verbose_name_plural': 'Amount of items'},
        ),
        migrations.AddField(
            model_name='balancelog',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance'),
        ),
    ]
