# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0007_auto_20161001_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancelog',
            name='arrival',
            field=models.BooleanField(default=False, verbose_name='arrival'),
        ),
    ]
