# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0008_auto_20161208_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unconditional'), (1, 'Order items count'), (2, 'Conditional')], default=0, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='categories',
        ),
        migrations.AddField(
            model_name='stocks',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='elephants.Categories'),
        ),
    ]
