# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0009_balancelog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancelog',
            options={'ordering': ('-change_time',), 'verbose_name': 'Balance log', 'verbose_name_plural': 'Balance logs'},
        ),
    ]
