# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0009_auto_20161214_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='items_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='items count'),
            preserve_default=False,
        ),
    ]
