# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0010_stocks_items_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='details_uk',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='fashions',
            name='details_uk',
        ),
        migrations.RemoveField(
            model_name='fashions',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='items',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='items',
            name='details_uk',
        ),
        migrations.RemoveField(
            model_name='items',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='items',
            name='price_description_uk',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='name_uk',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='categories',
            field=models.ManyToManyField(blank=True, to='elephants.Categories'),
        ),
    ]
