# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0010_auto_20161005_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_views',
            name='item',
        ),
        migrations.DeleteModel(
            name='Items_views',
        ),
    ]
