# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0011_auto_20161008_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('-views',), 'verbose_name': 'items', 'verbose_name_plural': 'items'},
        ),
        migrations.RemoveField(
            model_name='items',
            name='views_per_month',
        ),
        migrations.AddField(
            model_name='items',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AddField(
            model_name='items',
            name='views_month',
            field=models.CharField(default=0, max_length=512, verbose_name='views month'),
        ),
        migrations.AddField(
            model_name='items',
            name='views_today',
            field=models.PositiveIntegerField(default=0, verbose_name='views today'),
        ),
    ]
