# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('comment', models.TextField(blank=True, default='', verbose_name='description')),
                ('moderated', models.BooleanField(default=False, verbose_name='moderated')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Reply_to_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('reply', models.TextField(blank=True, default='', verbose_name='description')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comments')),
            ],
            options={
                'verbose_name': 'Reply_to_comments',
                'verbose_name_plural': 'Reply_to_comments',
            },
        ),
    ]
