# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0021_auto_20180215_1314'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elephants.Items'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elephants.Sets'),
        ),
    ]
