# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20180302_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_to_comments',
            name='city',
        ),
        migrations.RemoveField(
            model_name='reply_to_comments',
            name='name',
        ),
    ]
