# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_reply_to_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Просмотрено'), (3, 'Отвечено')], default=2, verbose_name='new status'),
        ),
    ]
