# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0023_auto_20180604_1352'),
        ('gallery', '0002_auto_20180603_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='items',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elephants.Items'),
        ),
    ]
