# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20161208_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='info_uk',
        ),
        migrations.RemoveField(
            model_name='info',
            name='title_uk',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='name_uk',
        ),
    ]
