# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20161216_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='info',
            name='title_uk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='stores',
            name='description_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='stores',
            name='name_uk',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
    ]
