# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:04
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20170411_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='infophoto',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='infophoto',
            name='small_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], keep_meta=True, quality=0, size=[300, 300], upload_to='small_info'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='small_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], keep_meta=True, quality=0, size=[300, 300], upload_to='small_info'),
        ),
    ]
