# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='price_description',
            field=models.CharField(default='Grn.', max_length=250, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_en',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_ru',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_uk',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
    ]
