# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20171213_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='price_description_eur',
            field=models.CharField(default='Eur.', max_length=250, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_eur_en',
            field=models.CharField(default='Eur.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_eur_ru',
            field=models.CharField(default='Eur.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_eur_uk',
            field=models.CharField(default='Eur.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_usd',
            field=models.CharField(default='Usd.', max_length=250, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_usd_en',
            field=models.CharField(default='Usd.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_usd_ru',
            field=models.CharField(default='Usd.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='config',
            name='price_description_usd_uk',
            field=models.CharField(default='Usd.', max_length=250, null=True, verbose_name='price_description'),
        ),
    ]
