# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20180213_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description_tag',
            field=models.CharField(blank=True, default='', max_length=280, verbose_name='description tag'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_tag_en',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_tag_ru',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description_tag_uk',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='description tag'),
        ),
    ]
