# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20180426_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='merchant_account',
            field=models.CharField(default='', max_length=64, verbose_name='merchant account'),
        ),
        migrations.AddField(
            model_name='config',
            name='merchant_domain_name',
            field=models.CharField(default='', max_length=64, verbose_name='merchant domain name'),
        ),
        migrations.AddField(
            model_name='config',
            name='service_url',
            field=models.CharField(default='', max_length=512, verbose_name='service URL'),
        ),
    ]
