# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20180512_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='merchant_secret',
            field=models.CharField(default='', max_length=128, verbose_name='merchant secret'),
        ),
    ]
