# Generated by Django 3.1.2 on 2020-12-01 11:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_config_merchant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='infophoto',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='infophoto',
            name='small_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_info'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[1500, 1500], upload_to='info'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='small_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_info'),
        ),
    ]
