# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name_plural': 'Amount of items',
                'verbose_name': 'Amount of items',
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.IntegerField(verbose_name='old value')),
                ('new_value', models.IntegerField(verbose_name='new value')),
                ('arrival', models.BooleanField(default=False, verbose_name='arrival')),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-change_time',),
                'verbose_name_plural': 'Balance logs',
                'verbose_name': 'Balance log',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('name_ru', models.CharField(max_length=70, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=70, null=True, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d')),
                ('image_hover', django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('details_ru', models.TextField(blank=True, null=True, verbose_name='details')),
                ('details_en', models.TextField(blank=True, null=True, verbose_name='details')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
            ],
            options={
                'ordering': ('sequence',),
                'verbose_name_plural': 'Categories of items',
                'verbose_name': 'Categories of items',
            },
        ),
        migrations.CreateModel(
            name='Fashions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=70, verbose_name='name')),
                ('name_ru', models.CharField(default='No name', max_length=70, null=True, verbose_name='name')),
                ('name_en', models.CharField(default='No name', max_length=70, null=True, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d')),
                ('image_hover', django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('details_ru', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('details_en', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Categories')),
            ],
            options={
                'ordering': ('sequence',),
                'verbose_name_plural': 'Fashions of items',
                'verbose_name': 'Fashions of items',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d')),
                ('image_small', django_resized.forms.ResizedImageField(upload_to='small_photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('details', models.TextField(blank=True, default='', verbose_name='details')),
                ('details_ru', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('details_en', models.TextField(blank=True, default='', null=True, verbose_name='details')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='price')),
                ('price_description', models.CharField(default='Grn.', max_length=250, verbose_name='price_description')),
                ('price_description_ru', models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description')),
                ('price_description_en', models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('views_today', models.PositiveIntegerField(default=0, verbose_name='views today')),
                ('views_month', models.CharField(default=0, max_length=512, verbose_name='views month')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('fashions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Fashions')),
            ],
            options={
                'ordering': ('-views',),
                'verbose_name_plural': 'items',
                'verbose_name': 'items',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(upload_to='photos/%Y/%m/%d')),
                ('image_small', django_resized.forms.ResizedImageField(upload_to='small_photos/%Y/%m/%d')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
            ],
            options={
                'ordering': ('added',),
                'verbose_name_plural': 'Photos',
                'verbose_name': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='sequence')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Categories')),
            ],
            options={
                'ordering': ('sequence',),
                'verbose_name_plural': 'Sizes of items',
                'verbose_name': 'Sizes of items',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items'),
        ),
        migrations.AddField(
            model_name='balance',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Sizes'),
        ),
    ]
