# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashions',
            name='displayed',
            field=models.BooleanField(default=True, verbose_name='displayed'),
        ),
    ]
