# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 21:53
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0002_fashions_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image_small',
            field=django_resized.forms.ResizedImageField(editable=False, upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=django_resized.forms.ResizedImageField(editable=False, upload_to='small_photos/%Y/%m/%d'),
        ),
    ]
