# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0006_auto_20161124_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
