# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0012_auto_20161223_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sets',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sets',
            name='details_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='sets',
            name='details_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='sets',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sets',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sets',
            name='price_description_en',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
        migrations.AddField(
            model_name='sets',
            name='price_description_ru',
            field=models.CharField(default='Grn.', max_length=250, null=True, verbose_name='price_description'),
        ),
    ]
