# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 09:38
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0013_auto_20161223_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
