# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0015_auto_20170411_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='fashions',
            field=models.ManyToManyField(blank=True, to='elephants.Fashions'),
        ),
    ]
