# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0017_fashions_weigth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_hover_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image_hover_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, keep_meta=True, quality=0, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, keep_meta=True, quality=0, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, keep_meta=True, quality=0, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='setsphoto',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='setsphoto',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, keep_meta=True, quality=0, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='items_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='items count'),
        ),
    ]
