# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0018_auto_20171008_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='showcase_displayed',
            field=models.BooleanField(default=True, verbose_name='showcase_displayed'),
        ),
    ]
