# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0022_items_price0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='price0',
        ),
        migrations.AddField(
            model_name='fashions',
            name='cost_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='cost price'),
        ),
    ]
