# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0023_auto_20180604_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, keep_meta=True, quality=0, size=[2500, 2500], upload_to='photos/%Y/%m/%d')),
                ('image_small', django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, keep_meta=True, quality=0, size=[300, 300], upload_to='small_photos/%Y/%m/%d')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ('added',),
            },
        ),
    ]
