# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0026_categories_showcase_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description_rozetka_d',
            field=models.TextField(blank=True, default='', verbose_name='descriptionrozetka d'),
        ),
    ]
