# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0027_items_description_rozetka_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, quality=0, size=[300, 150], upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Artists',
                'verbose_name': 'Artists',
            },
        ),
    ]
