# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0029_auto_20191026_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elephants.Artists'),
        ),
    ]
