# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-02-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0030_items_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='details_rozetka',
            field=models.TextField(blank=True, default='', verbose_name='details rozetka'),
        ),
    ]
