# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-04-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0031_items_details_rozetka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elephants.Artists'),
        ),
    ]
