# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0033_items_price_old_rozetka'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='showcase_avail',
            field=models.BooleanField(default=False, verbose_name='showcase_avail'),
        ),
        migrations.AddField(
            model_name='items',
            name='showcase_new',
            field=models.BooleanField(default=True, verbose_name='showcase_new'),
        ),
    ]
