# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-05 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0034_auto_20200624_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price_promo',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='price promo rozetka'),
        ),
    ]
