# Generated by Django 3.1.2 on 2020-12-01 11:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0035_items_price_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image_hover_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image_hover',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='fashions',
            name='image_hover_en',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[300, 150], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='items',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='rphoto',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='rphoto',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sets',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='setsphoto',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='setsphoto',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], editable=False, force_format=None, keep_meta=True, quality=90, size=[300, 300], upload_to='small_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=90, size=[2500, 2500], upload_to='photos/%Y/%m/%d'),
        ),
    ]
