# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32, verbose_name='name')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'ordering': ('added',),
                'verbose_name': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Items')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Sizes')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
            ],
            options={
                'verbose_name_plural': 'Order items',
                'ordering': ('added',),
                'verbose_name': 'Order item',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('phone', models.CharField(max_length=32, verbose_name='phone')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('delivery', models.IntegerField(choices=[(0, '* Delivery'), (1, 'Nova Poshta'), (2, 'Delivery to Odessa'), (3, 'Another embodiment')], default=0, verbose_name='delivery')),
                ('payment', models.IntegerField(choices=[(0, '* Payment'), (1, 'Cash on delivery'), (2, 'At stake Privat'), (3, 'Payment by courier')], default=0, verbose_name='payment')),
                ('status', models.IntegerField(choices=[(0, '* Status'), (1, 'New'), (2, 'Decorated'), (3, 'Ready to ship'), (4, 'Sent'), (9, 'Archived')], default=0, verbose_name='status')),
                ('ttn', models.IntegerField(default=0, verbose_name='TTN')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS sent')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ('-added',),
                'verbose_name': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
    ]
