# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elephants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=32, verbose_name='name')),
                ('amount', models.SmallIntegerField(default=1, verbose_name='amount')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
            ],
            options={
                'verbose_name': 'Cart',
                'ordering': ('added',),
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephants.Balance')),
            ],
            options={
                'verbose_name': 'Order items',
                'ordering': ('order',),
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='number')),
                ('name', models.CharField(default='No name', max_length=70, verbose_name='name')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='phone')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email')),
                ('city', models.CharField(default='', max_length=32, verbose_name='city')),
                ('delivery', models.CharField(default=0, max_length=32, verbose_name='delivery')),
                ('payment', models.CharField(default=0, max_length=32, verbose_name='payment')),
                ('massage', models.TextField(default='', verbose_name='massage')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Decorated'), (2, 'Ready to ship'), (3, 'Sent')], default=0, verbose_name='status')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name': 'orders',
                'ordering': ('-added',),
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
    ]
