# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160927_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='massage',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
        migrations.AddField(
            model_name='orders',
            name='message',
            field=models.TextField(default='', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=70, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='phone'),
        ),
    ]
