# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160927_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='message',
        ),
        migrations.AddField(
            model_name='orders',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Nova Post'), (2, 'Delivery to Odessa'), (3, 'Another embodiment')], default=0, verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Cash on delivery'), (2, 'At stake Privat'), (3, 'Payment by courier')], default=0, verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, '---'), (1, 'New'), (2, 'Decorated'), (3, 'Ready to ship'), (4, 'Sent')], default=0, verbose_name='status'),
        ),
    ]
