# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20161005_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
