# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitems_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ('added',), 'verbose_name': 'Order items', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='added'),
            preserve_default=False,
        ),
    ]
