# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20161006_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.IntegerField(choices=[(0, '* Delivery'), (1, 'Nova Poshta'), (2, 'Delivery to Odessa'), (3, 'Another embodiment')], default=0, verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.IntegerField(choices=[(0, '* Payment'), (1, 'Cash on delivery'), (2, 'At stake Privat'), (3, 'Payment by courier')], default=0, verbose_name='payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, '* Status'), (1, 'New'), (2, 'Decorated'), (3, 'Ready to ship'), (4, 'Sent'), (9, 'Archived')], default=0, verbose_name='status'),
        ),
    ]
