# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161008_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ('added',), 'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-added',), 'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='archived',
        ),
    ]
