# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161103_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='liqpay sender phone'),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, max_length=512, verbose_name='liqpay token'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_method',
            field=models.IntegerField(choices=[(0, 'Nova Poshta'), (1, 'Nova Poshta courier'), (2, 'Odessa courier'), (3, 'Another')], default=0, verbose_name='delivery_method'),
        ),
    ]
