# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20161008_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ttn',
            field=models.IntegerField(default=0, verbose_name='TTN'),
        ),
    ]
