# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders_ttn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comment'),
        ),
    ]
