# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0013_auto_20161223_1554'),
        ('orders', '0017_auto_20161214_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sets',
            field=models.ManyToManyField(blank=True, to='elephants.Sets'),
        ),
    ]
