# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elephants', '0013_auto_20161223_1554'),
        ('orders', '0021_auto_20170131_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartset',
            name='item',
        ),
        migrations.AddField(
            model_name='cartset',
            name='set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='elephants.Sets'),
            preserve_default=False,
        ),
    ]
