# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_cartsetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(default=' ', max_length=70, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=70, verbose_name='first name'),
        ),
    ]
