# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20170213_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount_set',
            field=models.PositiveIntegerField(default=0, verbose_name='discount from set'),
        ),
    ]
